export const EVENT_SOURCES = {
  WEATHER: "WEATHER",
  SOCIAL: "SOCIAL"
};

export const EVENT_STATUS = {
  DETECTED: "DETECTED",
  PENDING_ADMIN_APPROVAL: "PENDING_ADMIN_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED"
};

export const CLAIM_STATUS = {
  ELIGIBLE: "ELIGIBLE",
  REJECTED: "REJECTED",
  ADMIN_REVIEW: "ADMIN_REVIEW",
  HOLD_RIDER_VERIFICATION: "HOLD_RIDER_VERIFICATION",
  APPROVED: "APPROVED",
  PAID: "PAID"
};

export const RISK_TIERS = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  REPEAT_HIGH: "REPEAT_HIGH"
};
